package io.github.lucunji.noitaqb.gui;

import io.github.lucunji.noitaqb.config.ConfigManager;
import io.github.lucunji.noitaqb.model.Backup;
import io.github.lucunji.noitaqb.utils.ArchiveMode;
import io.github.lucunji.noitaqb.utils.BackupUtils;
import org.apache.commons.compress.archivers.ArchiveException;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ContainerAdapter;
import java.awt.event.ContainerEvent;
import java.io.IOException;
import java.nio.file.Path;

public class MainWindow {
    public JPanel rootPane;
    private JButton backupButton;
    private JButton loadButton;
    private JButton qbButton;
    private JPanel backupsPanel;
    private JButton refreshButton;

    private final ConfigManager cfgManager;

    private final ButtonGroup backupEntriesGroup;

    public MainWindow(ConfigManager cfgManager) {
        this.cfgManager = cfgManager;

        // UI editor in Intellij IDEA does not have BoxLayout
        var layout = new BoxLayout(backupsPanel, BoxLayout.Y_AXIS);
        backupsPanel.setLayout(layout);

        backupButton.addActionListener(this::onBackupButtonClicked);
        loadButton.addActionListener(this::onLoadButtonClicked);
        qbButton.addActionListener(this::onQbButtonClicked);
        refreshButton.addActionListener(this::onRefreshButtonClicked);
        backupsPanel.addContainerListener(new ContainerAdapter() {
            @Override
            public void componentRemoved(ContainerEvent e) {
                var component = e.getChild();
                if (component instanceof BackupEntryPanel) {
                    ((BackupEntryPanel) component).deregisterRadioButton(backupEntriesGroup);
                }
            }
        });

        backupEntriesGroup = new ButtonGroup();

        reloadBackups();
    }

    private void onBackupButtonClicked(ActionEvent event) {
        var name = JOptionPane.showInputDialog(
                "Backup name",
                "backup-" + System.currentTimeMillis()
        );
        if (name == null) return;
        addBackup(name);
    }

    private void onQbButtonClicked(ActionEvent event) {
        var name = "quickbackup-" + System.currentTimeMillis();
        addBackup(name);
    }

    private void onLoadButtonClicked(ActionEvent event) {
        Path path = null;
        for (var c : backupsPanel.getComponents()) {
            if (c instanceof BackupEntryPanel && ((BackupEntryPanel) c).isSelected()) {
                path = ((BackupEntryPanel) c).getBackup().getPath();
                break;
            }
        }
        if (path == null) {
            JOptionPane.showMessageDialog(this.rootPane, "No backup is selected");
            return;
        }
        if (!path.toFile().isFile()) {
            JOptionPane.showMessageDialog(this.rootPane, "Backup not found", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        var replacedSaveName = "quickbackup-" + System.currentTimeMillis() + " (replaced)";
        addBackup(replacedSaveName);

        try {
            BackupUtils.loadBackup(path, cfgManager.getConfigs().getGeneral().getSavePath());
        } catch (IOException | ArchiveException e) {
            throw new RuntimeException(e);
        }
    }

    private void onRefreshButtonClicked(ActionEvent event) {
        reloadBackups();
    }

    private void reloadBackups() {
        this.backupsPanel.removeAll();

        String backupPath = cfgManager.getConfigs().getGeneral().getBackupPath();
        Backup[] backups;
        try {
            backups = BackupUtils.loadBackups(backupPath);
        } catch (Exception e) {
            backups = new Backup[]{};
            System.out.println("Could not load backups in directory " + backupPath);
            e.printStackTrace();
        }
        for (Backup backup : backups) {
            var save = makeBackupPanel(backup);
            backupsPanel.add(save);
        }
        backupsPanel.repaint();
        backupsPanel.revalidate();
    }

    private void addBackup(String name) {
        final ArchiveMode mode = ArchiveMode.ZIP_ARCHIVE;

        var cfgGeneral = cfgManager.getConfigs().getGeneral();
        Backup backup;
        try {
            backup = BackupUtils.makeBackup(name, cfgGeneral.getBackupPath(), cfgGeneral.getSavePath(), mode);
        } catch (IOException | ArchiveException e) {
            throw new RuntimeException(e);
        }
        var save = makeBackupPanel(backup);
        backupsPanel.add(save, 0);

        backupsPanel.repaint();
        backupsPanel.revalidate();
    }

    private JPanel makeBackupPanel(Backup backup) {
        return new BackupEntryPanel(backup, backupEntriesGroup);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPane = new JPanel();
        rootPane.setLayout(new BorderLayout(0, 0));
        final JTabbedPane tabbedPane1 = new JTabbedPane();
        rootPane.add(tabbedPane1, BorderLayout.CENTER);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        tabbedPane1.addTab("Backup", panel1);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel1.add(panel2, BorderLayout.SOUTH);
        backupButton = new JButton();
        backupButton.setText("Backup");
        panel2.add(backupButton);
        qbButton = new JButton();
        qbButton.setText("Quick Backup");
        panel2.add(qbButton);
        loadButton = new JButton();
        loadButton.setText("Load");
        panel2.add(loadButton);
        refreshButton = new JButton();
        refreshButton.setText("Refresh");
        panel2.add(refreshButton);
        final JScrollPane scrollPane1 = new JScrollPane();
        panel1.add(scrollPane1, BorderLayout.CENTER);
        backupsPanel = new JPanel();
        backupsPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        scrollPane1.setViewportView(backupsPanel);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPane;
    }
}
